<?php echo CHtml::form('','post',array('enctype'=>'multipart/form-data')); ?>
...
<?php $model = new ImageUpload();  echo CHtml::activeFileField($model, 'uploaded'); ?>
...
<?php echo CHtml::endForm(); ?>